import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

const DEFAULT_REPO = "ShaharPeretz1/feedback-copilot";

// POST /api/tasks/[id]/export  -> create a GitHub issue for the task and store its URL.
// Requires GITHUB_TOKEN (a PAT or fine-grained token with issues:write on the repo).
export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO ?? DEFAULT_REPO;

  if (!token) {
    return NextResponse.json(
      { error: "Set GITHUB_TOKEN in the environment to export tasks to GitHub Issues." },
      { status: 400 }
    );
  }

  const task = await prisma.task.findUnique({ where: { id } });
  if (!task) return NextResponse.json({ error: "Task not found" }, { status: 404 });
  // Idempotent: don't open a second issue for an already-exported task.
  if (task.externalUrl) return NextResponse.json({ url: task.externalUrl, alreadyExported: true });

  const sourceLine =
    task.source === "FEEDBACK_THEME"
      ? `Source: customer-feedback theme (\`${task.themeId}\`)`
      : `Source: monitoring event (\`${task.monitorEventId}\`)`;
  const body = [
    task.description ?? "",
    "",
    `- **Severity:** ${task.severity}`,
    `- **Effort:** ${task.effort}`,
    `- **Impact score:** ${task.impactScore}`,
    task.area ? `- **Area:** ${task.area}` : "",
    "",
    sourceLine,
    "",
    "_Generated by Feedback Copilot._",
  ]
    .filter((l) => l !== null)
    .join("\n");

  let res: Response;
  try {
    res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title: task.title, body }),
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "network error";
    return NextResponse.json({ error: `Could not reach GitHub: ${message}` }, { status: 502 });
  }

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    return NextResponse.json(
      { error: `GitHub API ${res.status}: ${text.slice(0, 200)}` },
      { status: 502 }
    );
  }

  const issue = (await res.json()) as { html_url?: string };
  const updated = await prisma.task.update({
    where: { id },
    data: { externalUrl: issue.html_url ?? null },
  });
  return NextResponse.json({ url: updated.externalUrl });
}
